services:
  agent-zero:
    container_name: agent-zero
    image: agent-zero-local:latest
    restart: unless-stopped
    volumes:
      - ../../:/a0
      - D:/GitHub/Agent0-Local/Data:/a0/usr
    ports:
      - "8080:80"